#
# Copyright (c) 2019      University of Houston. All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#
include ../Makefile.defs

HEADER =  pepXML.Generated.altProteinDataType.h \
	  pepXML.Generated.asapratio_contribution.h \
	  pepXML.Generated.asapratio_lc_heavypeak.h \
	  pepXML.Generated.asapratio_lc_lightpeak.h \
	  pepXML.Generated.asapratio_peptide_data.h \
	  pepXML.Generated.asapratio_result.h \
	  pepXML.Generated.asapratio_summary.h \
	  pepXML.Generated.asapratio_timestamp.h \
	  pepXML.Generated.database_refresh_timestamp.h \
	  pepXML.Generated.inputFileType.h \
	  pepXML.Generated.interact_summary.h \
	  pepXML.Generated.interprophet_result.h \
	  pepXML.Generated.interprophet_summary.h \
	  pepXML.Generated.libra_result.h \
	  pepXML.Generated.libra_resultIntensity.h \
	  pepXML.Generated.libra_summaryContributing_channelAffected_channel.h \
	  pepXML.Generated.libra_summaryContributing_channel.h \
	  pepXML.Generated.libra_summaryFragment_masses.h \
	  pepXML.Generated.libra_summary.h \
	  pepXML.Generated.mixtureModelType.h \
	  pepXML.Generated.mixtureModelTypePoint.h \
	  pepXML.Generated.modInfoDataType.h \
	  pepXML.Generated.modInfoDataTypeMod_aminoacid_mass.h \
	  pepXML.Generated.msms_pipeline_analysisAnalysis_summary.h \
	  pepXML.Generated.msms_pipeline_analysisDataset_derivationData_filter.h \
	  pepXML.Generated.msms_pipeline_analysisDataset_derivation.h \
	  pepXML.Generated.msms_pipeline_analysis.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summaryAnalysis_timestamp.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summaryCross_linker.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summary.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySample_enzyme.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySample_enzymeSpecificity.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summaryAminoacid_modification.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summaryEnzymatic_search_constraint.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summary.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summarySearch_database.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summarySequence_search_constraint.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summaryTerminal_modification.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_query.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_querySearch_result.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_querySearch_resultSearch_hitAnalysis_result.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_querySearch_resultSearch_hit.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_querySearch_resultSearch_hitXlink.h \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_querySearch_resultSearch_hitXlinkLinked_peptide.h \
	  pepXML.Generated.nameValueType.h \
	  pepXML.Generated.peptideprophet_result.h \
	  pepXML.Generated.peptideprophet_summaryDistribution_point.h \
	  pepXML.Generated.peptideprophet_summary.h \
	  pepXML.Generated.peptideprophet_summaryMixture_model.h \
	  pepXML.Generated.peptideprophet_summaryMixture_modelMixturemodel_distribution.h \
	  pepXML.Generated.peptideprophet_summaryMixture_modelMixturemodel_distributionNegmodel_distribution.h \
	  pepXML.Generated.peptideprophet_summaryMixture_modelMixturemodel_distributionPosmodel_distribution.h \
	  pepXML.Generated.peptideprophet_summaryMixture_modelMixturemodel.h \
	  pepXML.Generated.peptideprophet_summaryMixture_modelMixturemodelPoint.h \
	  pepXML.Generated.ptmprophet_result.h \
	  pepXML.Generated.ptmprophet_resultMod_aminoacid_probability.h \
	  pepXML.Generated.ptmprophet_summary.h \
	  pepXML.Generated.rocErrorDataTypeError_point.h \
	  pepXML.Generated.rocErrorDataType.h \
	  pepXML.Generated.rocErrorDataTypeRoc_data_point.h \
	  pepXML.Generated.subInfoDataType.h \
	  pepXML.Generated.xpressratio_result.h \
	  pepXML.Generated.xpressratio_summary.h \
	  pepXML.Generated.xpressratio_timestamp.h \
	  pepXML_v120.h 


OBJ =     pepXML.Generated.altProteinDataType.o \
	  pepXML.Generated.asapratio_contribution.o \
	  pepXML.Generated.asapratio_lc_heavypeak.o \
	  pepXML.Generated.asapratio_lc_lightpeak.o \
	  pepXML.Generated.asapratio_peptide_data.o \
	  pepXML.Generated.asapratio_result.o \
	  pepXML.Generated.asapratio_summary.o \
	  pepXML.Generated.asapratio_timestamp.o \
	  pepXML.Generated.database_refresh_timestamp.o \
	  pepXML.Generated.inputFileType.o \
	  pepXML.Generated.interact_summary.o \
	  pepXML.Generated.interprophet_result.o \
	  pepXML.Generated.interprophet_summary.o \
	  pepXML.Generated.libra_result.o \
	  pepXML.Generated.libra_resultIntensity.o \
	  pepXML.Generated.libra_summaryContributing_channelAffected_channel.o \
	  pepXML.Generated.libra_summaryContributing_channel.o \
	  pepXML.Generated.libra_summaryFragment_masses.o \
	  pepXML.Generated.libra_summary.o \
	  pepXML.Generated.mixtureModelType.o \
	  pepXML.Generated.mixtureModelTypePoint.o \
	  pepXML.Generated.modInfoDataType.o \
	  pepXML.Generated.modInfoDataTypeMod_aminoacid_mass.o \
	  pepXML.Generated.msms_pipeline_analysisDataset_derivationData_filter.o \
	  pepXML.Generated.msms_pipeline_analysisDataset_derivation.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summaryCross_linker.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySample_enzyme.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySample_enzymeSpecificity.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summaryAminoacid_modification.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summaryEnzymatic_search_constraint.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summarySequence_search_constraint.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summaryTerminal_modification.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_query.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_querySearch_result.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_querySearch_resultSearch_hitXlink.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_querySearch_resultSearch_hitXlinkLinked_peptide.o \
	  pepXML.Generated.nameValueType.o \
	  pepXML.Generated.peptideprophet_result.o \
	  pepXML.Generated.peptideprophet_summaryDistribution_point.o \
	  pepXML.Generated.peptideprophet_summary.o \
	  pepXML.Generated.peptideprophet_summaryMixture_model.o \
	  pepXML.Generated.peptideprophet_summaryMixture_modelMixturemodel_distribution.o \
	  pepXML.Generated.peptideprophet_summaryMixture_modelMixturemodel_distributionNegmodel_distribution.o \
	  pepXML.Generated.peptideprophet_summaryMixture_modelMixturemodel_distributionPosmodel_distribution.o \
	  pepXML.Generated.peptideprophet_summaryMixture_modelMixturemodel.o \
	  pepXML.Generated.peptideprophet_summaryMixture_modelMixturemodelPoint.o \
	  pepXML.Generated.ptmprophet_result.o \
	  pepXML.Generated.ptmprophet_resultMod_aminoacid_probability.o \
	  pepXML.Generated.ptmprophet_summary.o \
	  pepXML.Generated.rocErrorDataTypeError_point.o \
	  pepXML.Generated.rocErrorDataType.o \
	  pepXML.Generated.rocErrorDataTypeRoc_data_point.o \
	  pepXML.Generated.subInfoDataType.o \
	  pepXML.Generated.xpressratio_summary.o \
	  pepXML.Generated.xpressratio_timestamp.o \
	  pepXML.Generated.msms_pipeline_analysis.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summaryAnalysis_timestamp.o \
	  pepXML.Generated.msms_pipeline_analysisAnalysis_summary.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summary.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summary.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySearch_summarySearch_database.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_querySearch_resultSearch_hitAnalysis_result.o \
	  pepXML.Generated.msms_pipeline_analysisMsms_run_summarySpectrum_querySearch_resultSearch_hit.o \
	  pepXML.Generated.xpressratio_result.o \
	  pepXML_v120.o 


.SUFFIXES: .o.cpp

all:    
	make $(MZLIB_LIB)
	cd XSD; make ; cd ..


$(MZLIB_LIB): $(HEADER) $(OBJ) 
	$(AR) $(AR_FLAGS) $(MZLIB_LIB_DIR)/$(MZLIB_LIB) $(OBJ)

$(OBJ):	$(HEADER)
.cpp.o:	$(HEADER)
	$(CXX) $(CXXFLAGS) $(CXXLOCALFLAGS) -c $<

clean:  
	rm -rf *.o *~
