#pragma once

#include "pepXML_v120.h"
#include <string>
#include <vector>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace pepXML { namespace Generated { class msms_pipeline_analysisMsms_run_summarySearch_summarySearch_database; } }
namespace pepXML { namespace Generated { class msms_pipeline_analysisMsms_run_summarySearch_summaryEnzymatic_search_constraint; } }
namespace pepXML { namespace Generated { class msms_pipeline_analysisMsms_run_summarySearch_summarySequence_search_constraint; } }
namespace pepXML { namespace Generated { class msms_pipeline_analysisMsms_run_summarySearch_summaryAminoacid_modification; } }
namespace pepXML { namespace Generated { class msms_pipeline_analysisMsms_run_summarySearch_summaryTerminal_modification; } }
namespace pepXML { namespace Generated { class nameValueType; } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace pepXML {
    namespace Generated {
        /// <remarks/>

            /// <remarks/>

            /// <remarks/>

        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://regis-web.systemsbiology.net/pepXML")] public partial class msms_pipeline_analysisMsms_run_summarySearch_summary
        class msms_pipeline_analysisMsms_run_summarySearch_summary {

        private:
            msms_pipeline_analysisMsms_run_summarySearch_summarySearch_database *search_databaseField;

            msms_pipeline_analysisMsms_run_summarySearch_summaryEnzymatic_search_constraint *enzymatic_search_constraintField;

            std::vector<msms_pipeline_analysisMsms_run_summarySearch_summarySequence_search_constraint*> sequence_search_constraintField;

            std::vector<msms_pipeline_analysisMsms_run_summarySearch_summaryAminoacid_modification*> aminoacid_modificationField;

            std::vector<msms_pipeline_analysisMsms_run_summarySearch_summaryTerminal_modification*> terminal_modificationField;

            std::vector<nameValueType*> parameterField;

            std::wstring base_nameField;

            engineType search_engineField = static_cast<engineType>(0);

            std::wstring search_engine_versionField;

            massType precursor_mass_typeField = static_cast<massType>(0);

            massType fragment_mass_typeField = static_cast<massType>(0);

            std::wstring out_data_typeField;

            std::wstring out_dataField;

            unsigned int search_idField = 0;

            /// <remarks/>
        public:
            virtual ~msms_pipeline_analysisMsms_run_summarySearch_summary() {
                delete search_databaseField;
                delete enzymatic_search_constraintField;
            }

            msms_pipeline_analysisMsms_run_summarySearch_summarySearch_database *getsearch_database() const;
            void setsearch_database(msms_pipeline_analysisMsms_run_summarySearch_summarySearch_database *value);

            /// <remarks/>
            msms_pipeline_analysisMsms_run_summarySearch_summaryEnzymatic_search_constraint *getenzymatic_search_constraint() const;
            void setenzymatic_search_constraint(msms_pipeline_analysisMsms_run_summarySearch_summaryEnzymatic_search_constraint *value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("sequence_search_constraint")] public msms_pipeline_analysisMsms_run_summarySearch_summarySequence_search_constraint[] sequence_search_constraint
            std::vector<msms_pipeline_analysisMsms_run_summarySearch_summarySequence_search_constraint*> getsequence_search_constraint() const;
            void setsequence_search_constraint(const std::vector<msms_pipeline_analysisMsms_run_summarySearch_summarySequence_search_constraint*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("aminoacid_modification")] public msms_pipeline_analysisMsms_run_summarySearch_summaryAminoacid_modification[] aminoacid_modification
            std::vector<msms_pipeline_analysisMsms_run_summarySearch_summaryAminoacid_modification*> getaminoacid_modification() const;
            void setaminoacid_modification(const std::vector<msms_pipeline_analysisMsms_run_summarySearch_summaryAminoacid_modification*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("terminal_modification")] public msms_pipeline_analysisMsms_run_summarySearch_summaryTerminal_modification[] terminal_modification
            std::vector<msms_pipeline_analysisMsms_run_summarySearch_summaryTerminal_modification*> getterminal_modification() const;
            void setterminal_modification(const std::vector<msms_pipeline_analysisMsms_run_summarySearch_summaryTerminal_modification*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("parameter")] public nameValueType[] parameter
            std::vector<nameValueType*> getparameter() const;
            void setparameter(const std::vector<nameValueType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string base_name
            std::wstring getbase_name() const;
            void setbase_name(const std::wstring &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public engineType search_engine
            engineType getsearch_engine() const;
            void setsearch_engine(engineType value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string search_engine_version
            std::wstring getsearch_engine_version() const;
            void setsearch_engine_version(const std::wstring &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public massType precursor_mass_type
            massType getprecursor_mass_type() const;
            void setprecursor_mass_type(massType value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public massType fragment_mass_type
            massType getfragment_mass_type() const;
            void setfragment_mass_type(massType value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string out_data_type
            std::wstring getout_data_type() const;
            void setout_data_type(const std::wstring &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string out_data
            std::wstring getout_data() const;
            void setout_data(const std::wstring &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public uint search_id
            unsigned int getsearch_id() const;
            void setsearch_id(unsigned int value);
        };
    }
}
