#pragma once

#include <string>

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace pepXML
{
    namespace Generated
    {
        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://regis-web.systemsbiology.net/pepXML")] public partial class peptideprophet_summaryDistribution_point
        class peptideprophet_summaryDistribution_point
        {

        private:
            float fvalueField = 0;

            std::string obs_1_distrField;

            float model_1_pos_distrField = 0;

            float model_1_neg_distrField = 0;

            std::string obs_2_distrField;

            float model_2_pos_distrField = 0;

            float model_2_neg_distrField = 0;

            std::string obs_3_distrField;

            float model_3_pos_distrField = 0;

            float model_3_neg_distrField = 0;

            std::string obs_4_distrField;

            float model_4_pos_distrField = 0;

            float model_4_neg_distrField = 0;

            std::string obs_5_distrField;

            float model_5_pos_distrField = 0;

            float model_5_neg_distrField = 0;

            std::string obs_6_distrField;

            float model_6_pos_distrField = 0;

            float model_6_neg_distrField = 0;

            std::string obs_7_distrField;

            float model_7_pos_distrField = 0;

            float model_7_neg_distrField = 0;

            /// <remarks/>
        public:
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float fvalue
            float getfvalue() const;
            void setfvalue(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")] public string obs_1_distr
            std::string getobs_1_distr() const;
            void setobs_1_distr(const std::string &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_1_pos_distr
            float getmodel_1_pos_distr() const;
            void setmodel_1_pos_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_1_neg_distr
            float getmodel_1_neg_distr() const;
            void setmodel_1_neg_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")] public string obs_2_distr
            std::string getobs_2_distr() const;
            void setobs_2_distr(const std::string &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_2_pos_distr
            float getmodel_2_pos_distr() const;
            void setmodel_2_pos_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_2_neg_distr
            float getmodel_2_neg_distr() const;
            void setmodel_2_neg_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")] public string obs_3_distr
            std::string getobs_3_distr() const;
            void setobs_3_distr(const std::string &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_3_pos_distr
            float getmodel_3_pos_distr() const;
            void setmodel_3_pos_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_3_neg_distr
            float getmodel_3_neg_distr() const;
            void setmodel_3_neg_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")] public string obs_4_distr
            std::string getobs_4_distr() const;
            void setobs_4_distr(const std::string &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_4_pos_distr
            float getmodel_4_pos_distr() const;
            void setmodel_4_pos_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_4_neg_distr
            float getmodel_4_neg_distr() const;
            void setmodel_4_neg_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")] public string obs_5_distr
            std::string getobs_5_distr() const;
            void setobs_5_distr(const std::string &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_5_pos_distr
            float getmodel_5_pos_distr() const;
            void setmodel_5_pos_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_5_neg_distr
            float getmodel_5_neg_distr() const;
            void setmodel_5_neg_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")] public string obs_6_distr
            std::string getobs_6_distr() const;
            void setobs_6_distr(const std::string &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_6_pos_distr
            float getmodel_6_pos_distr() const;
            void setmodel_6_pos_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_6_neg_distr
            float getmodel_6_neg_distr() const;
            void setmodel_6_neg_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")] public string obs_7_distr
            std::string getobs_7_distr() const;
            void setobs_7_distr(const std::string &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_7_pos_distr
            float getmodel_7_pos_distr() const;
            void setmodel_7_pos_distr(float value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public float model_7_neg_distr
            float getmodel_7_neg_distr() const;
            void setmodel_7_neg_distr(float value);
        };
    }
}
