#pragma once

#include <string>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace pepXML { namespace Generated { class peptideprophet_summaryMixture_modelMixturemodel_distributionPosmodel_distribution; } }
namespace pepXML { namespace Generated { class peptideprophet_summaryMixture_modelMixturemodel_distributionNegmodel_distribution; } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace pepXML {
    namespace Generated {
        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://regis-web.systemsbiology.net/pepXML")] public partial class peptideprophet_summaryMixture_modelMixturemodel_distribution
        class peptideprophet_summaryMixture_modelMixturemodel_distribution {

        private:
            peptideprophet_summaryMixture_modelMixturemodel_distributionPosmodel_distribution *posmodel_distributionField;

            peptideprophet_summaryMixture_modelMixturemodel_distributionNegmodel_distribution *negmodel_distributionField;

            std::wstring nameField;

            /// <remarks/>
        public:
            virtual ~peptideprophet_summaryMixture_modelMixturemodel_distribution() {
                delete posmodel_distributionField;
                delete negmodel_distributionField;
            }

            peptideprophet_summaryMixture_modelMixturemodel_distributionPosmodel_distribution *getposmodel_distribution() const;
            void setposmodel_distribution(peptideprophet_summaryMixture_modelMixturemodel_distributionPosmodel_distribution *value);

            /// <remarks/>
            peptideprophet_summaryMixture_modelMixturemodel_distributionNegmodel_distribution *getnegmodel_distribution() const;
            void setnegmodel_distribution(peptideprophet_summaryMixture_modelMixturemodel_distributionNegmodel_distribution *value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string name
            std::wstring getname() const;
            void setname(const std::wstring &value);
        };
    }
}
