#pragma once

#include <string>
#include <vector>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace pepXML { namespace Generated { class msms_pipeline_analysisAnalysis_summary; } }
namespace pepXML { namespace Generated { class msms_pipeline_analysisDataset_derivation; } }
namespace pepXML { namespace Generated { class msms_pipeline_analysisMsms_run_summary; } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




namespace pepXML {
    namespace Generated {
        // 
        // This source code was auto-generated by xsd, Version=4.7.2046.0.
        // 


        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://regis-web.systemsbiology.net/pepXML")][System.Xml.Serialization.XmlRootAttribute(Namespace = "http://regis-web.systemsbiology.net/pepXML", IsNullable = false)] public partial class msms_pipeline_analysis
        class msms_pipeline_analysis {

        private:
            std::vector<msms_pipeline_analysisAnalysis_summary*> analysis_summaryField;

            std::vector<msms_pipeline_analysisDataset_derivation*> dataset_derivationField;

            std::vector<msms_pipeline_analysisMsms_run_summary*> msms_run_summaryField;

            std::wstring nameField;

            DateTime dateField;

            std::wstring summary_xmlField;

            /// <remarks/>
        public:
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("analysis_summary")] public msms_pipeline_analysisAnalysis_summary[] analysis_summary
            std::vector<msms_pipeline_analysisAnalysis_summary*> getanalysis_summary() const;
            void setanalysis_summary(const std::vector<msms_pipeline_analysisAnalysis_summary*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("dataset_derivation")] public msms_pipeline_analysisDataset_derivation[] dataset_derivation
            std::vector<msms_pipeline_analysisDataset_derivation*> getdataset_derivation() const;
            void setdataset_derivation(const std::vector<msms_pipeline_analysisDataset_derivation*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("msms_run_summary")] public msms_pipeline_analysisMsms_run_summary[] msms_run_summary
            std::vector<msms_pipeline_analysisMsms_run_summary*> getmsms_run_summary() const;
            void setmsms_run_summary(const std::vector<msms_pipeline_analysisMsms_run_summary*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string name
            std::wstring getname() const;
            void setname(const std::wstring &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public System.DateTime date
            DateTime getdate() const;
            void setdate(DateTime value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string summary_xml
            std::wstring getsummary_xml() const;
            void setsummary_xml(const std::wstring &value);


//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [XmlAttributeAttribute("schemaLocation", Namespace = "http://www.w3.org/2001/XMLSchema-instance")] public string xsiSchemaLocation = "http://regis-web.systemsbiology.net/pepXML http://sashimi.sourceforge.net/schema_revision/pepXML/pepXML_v120.xsd";
            std::wstring xsiSchemaLocation = L"http://regis-web.systemsbiology.net/pepXML http://sashimi.sourceforge.net/schema_revision/pepXML/pepXML_v120.xsd";
        };
    }
}
