#pragma once

#include <vector>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace IO { namespace MzML { namespace Generated { class ParamGroupType; } } }
namespace IO { namespace MzML { namespace Generated { class SourceFileListType; } } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IO
{
    namespace MzML
    {
        namespace Generated
        {
        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")] public partial class FileDescriptionType
        class FileDescriptionType
        {

        private:
            ParamGroupType *fileContentField;

            SourceFileListType *sourceFileListField;

            std::vector<ParamGroupType*> contactField;

            /// <remarks/>
        public:
            virtual ~FileDescriptionType()
            {
                delete fileContentField;
                delete sourceFileListField;
            }

            ParamGroupType *getfileContent() const;
            void setfileContent(ParamGroupType *value);

            /// <remarks/>
            SourceFileListType *getsourceFileList() const;
            void setsourceFileList(SourceFileListType *value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("contact")] public ParamGroupType[] contact
            std::vector<ParamGroupType*> getcontact() const;
            void setcontact(const std::vector<ParamGroupType*> &value);
        };
        }
    }
}
