#pragma once

#include "IO.MzML.Generated.ParamGroupType.h"
#include <string>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace IO { namespace MzML { namespace Generated { class ComponentListType; } } }
namespace IO { namespace MzML { namespace Generated { class SoftwareRefType; } } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IO {
    namespace MzML {
        namespace Generated {
        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")] public partial class InstrumentConfigurationType: ParamGroupType
        class InstrumentConfigurationType : public ParamGroupType {

        private:
            ComponentListType *componentListField;

            SoftwareRefType *softwareRefField;

            std::wstring idField;

            std::wstring scanSettingsRefField;

            /// <remarks/>
        public:
            virtual ~InstrumentConfigurationType() {
                delete componentListField;
                delete softwareRefField;
            }

            ComponentListType *getcomponentList() const;
            void setcomponentList(ComponentListType *value);

            /// <remarks/>
            SoftwareRefType *getsoftwareRef() const;
            void setsoftwareRef(SoftwareRefType *value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")] public string id
            std::wstring getid() const;
            void setid(const std::wstring &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")] public string scanSettingsRef
            std::wstring getscanSettingsRef() const;
            void setscanSettingsRef(const std::wstring &value);
        };
        }
    }
}
