#pragma once

#include <string>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace IO { namespace MzML { namespace Generated { class ParamGroupType; } } }
namespace IO { namespace MzML { namespace Generated { class SelectedIonListType; } } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IO
{
    namespace MzML
    {
        namespace Generated
        {
        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")] public partial class PrecursorType
        class PrecursorType
        {

        private:
            ParamGroupType *isolationWindowField;

            SelectedIonListType *selectedIonListField;

            ParamGroupType *activationField;

            std::string spectrumRefField;

            std::string sourceFileRefField;

            std::string externalSpectrumIDField;

            /// <remarks/>
        public:
            virtual ~PrecursorType()
            {
                delete isolationWindowField;
                delete selectedIonListField;
                delete activationField;
            }

            ParamGroupType *getisolationWindow() const;
            void setisolationWindow(ParamGroupType *value);

            /// <remarks/>
            SelectedIonListType *getselectedIonList() const;
            void setselectedIonList(SelectedIonListType *value);

            /// <remarks/>
            ParamGroupType *getactivation() const;
            void setactivation(ParamGroupType *value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string spectrumRef
            std::string getspectrumRef() const;
            void setspectrumRef(const std::string &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")] public string sourceFileRef
            std::string getsourceFileRef() const;
            void setsourceFileRef(const std::string &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string externalSpectrumID
            std::string getexternalSpectrumID() const;
            void setexternalSpectrumID(const std::string &value);
        };
        }
    }
}
