#pragma once

#include <vector>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace mzIdentML110 { namespace Generated { class SourceFileType; } }
namespace mzIdentML110 { namespace Generated { class SearchDatabaseType; } }
namespace mzIdentML110 { namespace Generated { class SpectraDataType; } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.7.2046.0.
// 

namespace mzIdentML110 {
    namespace Generated {
        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://psidev.info/psi/pi/mzIdentML/1.1")] public partial class InputsType
        class InputsType {

        private:
            std::vector<SourceFileType*> sourceFileField;

            std::vector<SearchDatabaseType*> searchDatabaseField;

            std::vector<SpectraDataType*> spectraDataField;

            /// <remarks/>
        public:
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("SourceFile")] public SourceFileType[] SourceFile
            std::vector<SourceFileType*> getSourceFile() const;
            void setSourceFile(const std::vector<SourceFileType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("SearchDatabase")] public SearchDatabaseType[] SearchDatabase
            std::vector<SearchDatabaseType*> getSearchDatabase() const;
            void setSearchDatabase(const std::vector<SearchDatabaseType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("SpectraData")] public SpectraDataType[] SpectraData
            std::vector<SpectraDataType*> getSpectraData() const;
            void setSpectraData(const std::vector<SpectraDataType*> &value);
        };
    }
}
