#pragma once

#include "mzIdentML.Generated.ProtocolApplicationType.h"
#include <string>
#include <vector>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace mzIdentML { namespace Generated { class InputSpectraType; } }
namespace mzIdentML { namespace Generated { class SearchDatabaseRefType; } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mzIdentML {
    namespace Generated {
        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://psidev.info/psi/pi/mzIdentML/1.1.1")] public partial class SpectrumIdentificationType: ProtocolApplicationType
        class SpectrumIdentificationType : public ProtocolApplicationType {

        private:
            std::vector<InputSpectraType*> inputSpectraField;

            std::vector<SearchDatabaseRefType*> searchDatabaseRefField;

            std::wstring spectrumIdentificationProtocol_refField;

            std::wstring spectrumIdentificationList_refField;

            /// <remarks/>
        public:
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("InputSpectra")] public InputSpectraType[] InputSpectra
            std::vector<InputSpectraType*> getInputSpectra() const;
            void setInputSpectra(const std::vector<InputSpectraType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("SearchDatabaseRef")] public SearchDatabaseRefType[] SearchDatabaseRef
            std::vector<SearchDatabaseRefType*> getSearchDatabaseRef() const;
            void setSearchDatabaseRef(const std::vector<SearchDatabaseRefType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string spectrumIdentificationProtocol_ref
            std::wstring getspectrumIdentificationProtocol_ref() const;
            void setspectrumIdentificationProtocol_ref(const std::wstring &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string spectrumIdentificationList_ref
            std::wstring getspectrumIdentificationList_ref() const;
            void setspectrumIdentificationList_ref(const std::wstring &value);
        };
    }
}
