#pragma once

#include "mzIdentML.Generated.IdentifiableType.h"
#include <vector>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace mzIdentML { namespace Generated { class MeasureType; } }
namespace mzIdentML { namespace Generated { class SpectrumIdentificationResultType; } }
namespace mzIdentML { namespace Generated { class CVParamType; } }
namespace mzIdentML { namespace Generated { class UserParamType; } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mzIdentML {
    namespace Generated {
        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://psidev.info/psi/pi/mzIdentML/1.1.1")] public partial class SpectrumIdentificationListType: IdentifiableType
        class SpectrumIdentificationListType : public IdentifiableType {

        private:
            std::vector<MeasureType*> fragmentationTableField;

            std::vector<SpectrumIdentificationResultType*> spectrumIdentificationResultField;

            std::vector<CVParamType*> cvParamField;

            std::vector<UserParamType*> userParamField;

            long long numSequencesSearchedField = 0;

            bool numSequencesSearchedFieldSpecified = false;

            /// <remarks/>
        public:
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("Measure", IsNullable = false)] public MeasureType[] FragmentationTable
            std::vector<MeasureType*> getFragmentationTable() const;
            void setFragmentationTable(const std::vector<MeasureType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("SpectrumIdentificationResult")] public SpectrumIdentificationResultType[] SpectrumIdentificationResult
            std::vector<SpectrumIdentificationResultType*> getSpectrumIdentificationResult() const;
            void setSpectrumIdentificationResult(const std::vector<SpectrumIdentificationResultType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("cvParam")] public CVParamType[] cvParam
            std::vector<CVParamType*> getcvParam() const;
            void setcvParam(const std::vector<CVParamType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("userParam")] public UserParamType[] userParam
            std::vector<UserParamType*> getuserParam() const;
            void setuserParam(const std::vector<UserParamType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public long numSequencesSearched
            long long getnumSequencesSearched() const;
            void setnumSequencesSearched(long long value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool numSequencesSearchedSpecified
            bool getnumSequencesSearchedSpecified() const;
            void setnumSequencesSearchedSpecified(bool value);
        };
    }
}
