#pragma once

#include "mzIdentML.Generated.IdentifiableType.h"
#include <string>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace mzIdentML { namespace Generated { class ContactRoleType; } }
namespace mzIdentML { namespace Generated { class ParamType; } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mzIdentML {
    namespace Generated {
        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://psidev.info/psi/pi/mzIdentML/1.1.1")] public partial class AnalysisSoftwareType: IdentifiableType
        class AnalysisSoftwareType : public IdentifiableType {

        private:
            ContactRoleType *contactRoleField;

            ParamType *softwareNameField;

            std::wstring customizationsField;

            std::wstring versionField;

            std::wstring uriField;

            /// <remarks/>
        public:
            virtual ~AnalysisSoftwareType() {
                delete contactRoleField;
                delete softwareNameField;
            }

            ContactRoleType *getContactRole() const;
            void setContactRole(ContactRoleType *value);

            /// <remarks/>
            ParamType *getSoftwareName() const;
            void setSoftwareName(ParamType *value);

            /// <remarks/>
            std::wstring getCustomizations() const;
            void setCustomizations(const std::wstring &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string version
            std::wstring getversion() const;
            void setversion(const std::wstring &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")] public string uri
            std::wstring geturi() const;
            void seturi(const std::wstring &value);
        };
    }
}
