#pragma once

#include "mzIdentML.Generated.IdentifiableType.h"
#include <string>
#include <vector>

//C# TO C++ CONVERTER NOTE: Forward class declarations:
namespace mzIdentML { namespace Generated { class ModificationType; } }
namespace mzIdentML { namespace Generated { class SubstitutionModificationType; } }
namespace mzIdentML { namespace Generated { class CVParamType; } }
namespace mzIdentML { namespace Generated { class UserParamType; } }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mzIdentML {
    namespace Generated {
        /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")][System.SerializableAttribute()][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://psidev.info/psi/pi/mzIdentML/1.1.1")] public partial class PeptideType: IdentifiableType
        class PeptideType : public IdentifiableType {

        private:
            std::wstring peptideSequenceField;

            std::vector<ModificationType*> modificationField;

            std::vector<SubstitutionModificationType*> substitutionModificationField;

            std::vector<CVParamType*> cvParamField;

            std::vector<UserParamType*> userParamField;

            /// <remarks/>
        public:
            std::wstring getPeptideSequence() const;
            void setPeptideSequence(const std::wstring &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("Modification")] public ModificationType[] Modification
            std::vector<ModificationType*> getModification() const;
            void setModification(const std::vector<ModificationType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("SubstitutionModification")] public SubstitutionModificationType[] SubstitutionModification
            std::vector<SubstitutionModificationType*> getSubstitutionModification() const;
            void setSubstitutionModification(const std::vector<SubstitutionModificationType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("cvParam")] public CVParamType[] cvParam
            std::vector<CVParamType*> getcvParam() const;
            void setcvParam(const std::vector<CVParamType*> &value);

            /// <remarks/>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Xml.Serialization.XmlElementAttribute("userParam")] public UserParamType[] userParam
            std::vector<UserParamType*> getuserParam() const;
            void setuserParam(const std::vector<UserParamType*> &value);
        };
    }
}
