#pragma once

#include "AminoAcidPolymer/AminoAcidPolymer.h"
#include "AminoAcidPolymer/ModificationCollection.h"
#include "AminoAcidPolymer/Peptide.h"
#include "AminoAcidPolymer/OldSchoolModification.h"
#include "AminoAcidPolymer/OldSchoolModificationWithMultiplePossibilities.h"
#include "AminoAcidPolymer/ModificationSites.h"
#include "AminoAcidPolymer/Residue.h"
#include "AminoAcidPolymer/Terminus.h"
#include "AminoAcidPolymer/Fragment.h"
#include "AminoAcidPolymer/FragmentTypes.h"
#include "AminoAcidPolymer/DigestionPoint.h"
#include "AminoAcidPolymer/ChemicalFormulaFragment.h"
#include "AminoAcidPolymer/ChemicalFormulaModification.h"
#include "AminoAcidPolymer/ChemicalFormulaTerminus.h"

#include "Modifications/Modification.h"
#include "Modifications/ModificationMotif.h"
#include "Modifications/ModificationLocalization.h"
#include "Modifications/ModLocationOnPeptideOrProtein.h"

#include "Protein/Protein.h"
#include "Protein/ProteolysisProduct.h"
#include "Protein/DatabaseReference.h"
#include "Protein/DisulfideBond.h"
#include "Protein/SequenceVariation.h"
#include "Protein/SequenceVariantDescription.h"
#include "Protein/SnpEffAnnotation.h"
#include "Protein/SpliceSite.h"
#include "Protein/VariantApplication.h"

#include  "Fragmentation/CompactPeptideBase.h"
#include  "Fragmentation/CompactPeptide.h"
#include  "Fragmentation/DissociationTypeCollection.h"
#include  "Fragmentation/Fragmentation.h"
#include  "Fragmentation/FragmentationTerminus.h"
#include  "Fragmentation/MatchedFragmentIon.h"
#include  "Fragmentation/NeutralTerminusFragment.h"
#include  "Fragmentation/Product.h"
#include  "Fragmentation/ProductType.h"
#include  "Fragmentation/TerminusSpecificProductTypes.h"
#include  "ProteolyticDigestion/CleavageSpecificity.h"
#include  "ProteolyticDigestion/DigestionMotif.h"
#include  "ProteolyticDigestion/DigestionParams.h"
#include  "ProteolyticDigestion/InitiatorMethionineBehavior.h"
#include  "ProteolyticDigestion/PeptideWithSetModifications.h"
#include  "ProteolyticDigestion/ProductTypeMethods.h"
#include  "ProteolyticDigestion/ProteaseDictionary.h"
#include  "ProteolyticDigestion/Protease.h"
#include  "ProteolyticDigestion/ProteinDigestion.h"
#include  "ProteolyticDigestion/ProteolyticPeptide.h"

