name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
         sudo apt-get install -y cereal libcereal-dev xsdcxx libxerces-c-dev
         ./configure
    - name: make
      run: make -j4
    - name: make check
      run: make check

