name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
         sudo apt-get update
         sudo apt-get install -y --fix-missing g++-9 cereal libcereal-dev xsdcxx libxerces-c-dev
         g++ --version
         g++-9 --version
         ./configure CXX=g++-9
    - name: make
      run: make -j4
    - name: make check
      run: make check

